-- =============================================================================
-- BALAJI SAVINGS & FINANCE - SUPABASE DATABASE SCHEMA
-- Execute this entire script inside the Supabase SQL Editor
-- (https://supabase.com/dashboard/project/mfxqnuvbafnpgzwmrkui/sql/new)
-- =============================================================================

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'admin',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. MEMBERS TABLE
CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    contact_no_1 TEXT NOT NULL,
    contact_no_2 TEXT,
    aadhaar_no TEXT NOT NULL,
    kyc_status TEXT NOT NULL DEFAULT 'Verified',
    chit_status TEXT NOT NULL DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. KYC DOCUMENTS TABLE
CREATE TABLE IF NOT EXISTS kyc_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
    document_type TEXT NOT NULL,
    file_name TEXT NOT NULL,
    original_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    file_size BIGINT NOT NULL,
    uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. CHIT SCHEMES TABLE
CREATE TABLE IF NOT EXISTS chit_schemes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheme_code TEXT UNIQUE NOT NULL,
    scheme_name TEXT NOT NULL,
    total_chit_value NUMERIC(15, 2) NOT NULL,
    duration_months INT NOT NULL,
    number_of_members INT NOT NULL,
    monthly_contribution NUMERIC(15, 2) NOT NULL,
    foreman_commission_percent NUMERIC(5, 2) NOT NULL DEFAULT 5.0,
    foreman_commission_amount NUMERIC(15, 2) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. CHIT ENROLLMENTS TABLE
CREATE TABLE IF NOT EXISTS chit_enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheme_id BIGINT REFERENCES chit_schemes(id) ON DELETE CASCADE,
    member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
    ticket_number INT NOT NULL,
    enrolled_at TIMESTAMPTZ DEFAULT NOW(),
    status TEXT NOT NULL DEFAULT 'Active',
    CONSTRAINT unq_scheme_ticket UNIQUE(scheme_id, ticket_number)
);

-- 6. AUCTIONS TABLE
CREATE TABLE IF NOT EXISTS auctions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheme_id BIGINT REFERENCES chit_schemes(id) ON DELETE CASCADE,
    month_number INT NOT NULL,
    auction_date DATE NOT NULL,
    winning_member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    winning_ticket_number INT DEFAULT 1,
    winning_bid_discount NUMERIC(15, 2) NOT NULL,
    foreman_commission NUMERIC(15, 2) NOT NULL,
    winner_payout NUMERIC(15, 2) NOT NULL,
    dividend_pool NUMERIC(15, 2) NOT NULL,
    dividend_per_member NUMERIC(15, 2) NOT NULL,
    next_month_payable NUMERIC(15, 2) NOT NULL,
    payout_mode TEXT DEFAULT 'Bank Transfer',
    payout_ref_no TEXT,
    payout_bank_name TEXT,
    payout_cheque_no TEXT,
    payout_cheque_date DATE,
    payout_proof_image TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unq_scheme_month UNIQUE(scheme_id, month_number)
);

-- 7. MONTHLY PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS monthly_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheme_id BIGINT REFERENCES chit_schemes(id) ON DELETE CASCADE,
    member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
    ticket_number INT DEFAULT 1,
    month_number INT NOT NULL,
    base_contribution NUMERIC(15, 2) NOT NULL,
    dividend_applied NUMERIC(15, 2) NOT NULL DEFAULT 0,
    net_amount_due NUMERIC(15, 2) NOT NULL,
    amount_paid NUMERIC(15, 2) NOT NULL DEFAULT 0,
    payment_date DATE,
    payment_mode TEXT DEFAULT 'Cash',
    reference_no TEXT,
    bank_name TEXT,
    cheque_no TEXT,
    cheque_date DATE,
    proof_image_data TEXT,
    status TEXT NOT NULL DEFAULT 'Pending',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unq_scheme_member_ticket_month UNIQUE(scheme_id, member_id, ticket_number, month_number)
);

-- 8. DIVIDENDS TABLE
CREATE TABLE IF NOT EXISTS dividends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auction_id BIGINT REFERENCES auctions(id) ON DELETE CASCADE,
    scheme_id BIGINT REFERENCES chit_schemes(id) ON DELETE CASCADE,
    member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
    ticket_number INT DEFAULT 1,
    month_number INT NOT NULL,
    dividend_amount NUMERIC(15, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. AUDIT LOGS TABLE
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    user_name TEXT,
    action TEXT NOT NULL,
    target TEXT NOT NULL,
    details TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================================================
-- INDEXES FOR PERFORMANCE OPTIMIZATION
-- =============================================================================
CREATE INDEX IF NOT EXISTS idx_members_code ON members(member_code);
CREATE INDEX IF NOT EXISTS idx_members_email ON members(email);
CREATE INDEX IF NOT EXISTS idx_schemes_code ON chit_schemes(scheme_code);
CREATE INDEX IF NOT EXISTS idx_enrollments_scheme ON chit_enrollments(scheme_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_member ON chit_enrollments(member_id);
CREATE INDEX IF NOT EXISTS idx_auctions_scheme ON auctions(scheme_id);
CREATE INDEX IF NOT EXISTS idx_payments_scheme ON monthly_payments(scheme_id);
CREATE INDEX IF NOT EXISTS idx_payments_member ON monthly_payments(member_id);
CREATE INDEX IF NOT EXISTS idx_dividends_auction ON dividends(auction_id);

-- =============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Enables full access for client/backend operations using Anon/Publishable Key
-- =============================================================================
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE kyc_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE chit_schemes ENABLE ROW LEVEL SECURITY;
ALTER TABLE chit_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE auctions ENABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE dividends ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- Create permissive RLS policies for Anon & Authenticated roles
DO $$ 
DECLARE
    tbl text;
BEGIN
    FOR tbl IN 
        SELECT table_name FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_name IN ('users', 'members', 'kyc_documents', 'chit_schemes', 'chit_enrollments', 'auctions', 'monthly_payments', 'dividends', 'audit_logs')
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Allow full access" ON %I;', tbl);
        EXECUTE format('CREATE POLICY "Allow full access" ON %I FOR ALL USING (true) WITH CHECK (true);', tbl);
    END LOOP;
END $$;

-- =============================================================================
-- INITIAL SEED DATA (Balaji Savings & Finance Default Data)
-- =============================================================================

-- Seed Admin User (Password: admin123)
INSERT INTO users (name, email, password_hash, role)
VALUES ('Admin Staff', 'admin@balajichit.com', '$2b$10$ZotvDiPG2u2nY3Gb.tIhy.izBiYmuPeTONyB3MACFiu7lfbExblt2', 'admin')
ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash;
